---
stand:
  hosts:
    gateway:
      networking_hostname: "{{ inventory_hostname_short }}"
      networking_mgmt_iface_nat: true
      networking_k8s_iface_cidr: 192.168.78.1/24
  vars:
    ansible_ssh_common_args: -F ssh/config
    ansible_python_interpreter: /usr/bin/python3
    networking_mgmt_iface_name: enp0s8
    networking_k8s_iface_name: enp0s9
  children:
    k8s:
      hosts:
        control-plane:
          networking_hostname: "{{ inventory_hostname_short }}"
          networking_k8s_iface_cidr: 192.168.78.10/24
          networking_k8s_gateway: 192.168.78.1
          controlplane_pod_network_cidr: 172.29.0.0/16
          controlplane_apiserver_address: 192.168.78.10
      children:
        workers:
          hosts:
            worker-alice-1:
              networking_hostname: "{{ inventory_hostname_short }}"
              networking_k8s_iface_cidr: 192.168.78.11/24
              networking_k8s_gateway: 192.168.78.1
            worker-alice-2:
              networking_hostname: "{{ inventory_hostname_short }}"
              networking_k8s_iface_cidr: 192.168.78.12/24
              networking_k8s_gateway: 192.168.78.1
            worker-mallory:
              networking_hostname: "{{ inventory_hostname_short }}"
              networking_k8s_iface_cidr: 192.168.78.13/24
              networking_k8s_gateway: 192.168.78.1
          vars:
            worker_control_plane_node: control-plane
            worker_apiserver_address: 192.168.78.10
