---
- name: Install Ansible dependencies
  hosts: stand
  gather_facts: false
  tasks:
    - name: Install Ansible dependencies
      ansible.builtin.raw: apt-get update && apt-get --yes install python3 python3-apt ca-certificates
      changed_when: true
