---
- name: Add Kubernetes apt key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: u=rw,g=r,o=r

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    state: present
    filename: kubernetes

- name: Install kubelet, kubectl and kubeadm
  ansible.builtin.apt:
    name:
      - kubelet
      - kubectl
      - kubeadm
    state: present

- name: Enable kubelet service
  ansible.builtin.systemd_service:
    name: containerd
    state: started
    enabled: true
