---
argument_specs:
  main:
    short_description: Install kubelet, kubectl and kubeadm
    description:
      - Install kubelet, kubectl and kubeadm.
    version_added: 0.1.0
    author:
      - Alexey Busygin
    options: {}
