---
- name: Add Docker apt key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: u=rw,g=r,o=r

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
    state: present
    filename: docker

- name: Install containerd
  ansible.builtin.apt:
    name:
      - containerd.io
    state: present

- name: Reset configuration
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  changed_when: true

- name: Configure the systemd cgroup driver
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    after: '\[plugins\."io.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options\]'
    regexp: \bSystemdCgroup = false\b
    replace: SystemdCgroup = true

- name: Restart containerd
  ansible.builtin.systemd_service:
    name: containerd
    state: restarted
